package pl.fanth.gitsync.git;

import com.google.gson.Gson;

import java.nio.file.FileSystems;
import java.nio.file.PathMatcher;
import java.util.ArrayList;
import java.util.Collection;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.stream.Stream;

/**
 * Model of pack.json living in the root of the synced repository.
 */
public class PackManifest {
    private static final Gson GSON = new Gson();

    public Map<String, Entry> plugins = new LinkedHashMap<>();

    public static class Entry {
        public String pluginJarWildcard;
        public List<String> configPaths = new ArrayList<>();
        public List<String> reloadCommands = new ArrayList<>();

        /** Does a repository-relative path belong to this plugin? */
        public boolean matches(String path) {
            if (this.configPaths != null) {
                for (String configPath : this.configPaths) {
                    String clean = normalize(configPath);
                    if (!clean.isEmpty() && (path.equals(clean) || path.startsWith(clean + "/"))) {
                        return true;
                    }
                }
            }
            if (this.pluginJarWildcard == null || this.pluginJarWildcard.isBlank()) {
                return false;
            }
            PathMatcher matcher = FileSystems.getDefault().getPathMatcher("glob:" + normalize(this.pluginJarWildcard));
            return matcher.matches(java.nio.file.Path.of(path));
        }
    }

    public static PackManifest parse(String json) {
        PackManifest manifest = GSON.fromJson(json, PackManifest.class);
        if (manifest == null) {
            manifest = new PackManifest();
        }
        if (manifest.plugins == null) {
            manifest.plugins = new LinkedHashMap<>();
        }
        return manifest;
    }

    /**
     * Ignore everything (including .gitignore itself), then re-include only what pack.json declares.
     * Parent directories have to be re-included explicitly, git never descends into an ignored directory.
     */
    public List<String> gitignoreLines() {
        Set<String> lines = new LinkedHashSet<>();
        lines.add("# Generated by GitSync from pack.json - do not edit");
        lines.add("/**");
        lines.add("!/pack.json");

        for (Entry entry : this.plugins.values()) {
            if (entry.pluginJarWildcard != null && !entry.pluginJarWildcard.isBlank()) {
                lines.add("!/" + normalize(entry.pluginJarWildcard));
            }
            if (entry.configPaths == null) {
                continue;
            }
            for (String configPath : entry.configPaths) {
                String clean = normalize(configPath);
                if (clean.isEmpty()) {
                    continue;
                }
                String[] parts = clean.split("/");
                StringBuilder parent = new StringBuilder();
                for (int i = 0; i < parts.length - 1; i++) {
                    parent.append('/').append(parts[i]);
                    lines.add("!" + parent + "/");
                }
                lines.add("!/" + clean);
                lines.add("!/" + clean + "/**");
            }
        }
        return new ArrayList<>(lines);
    }

    /** Returns the list of plugin entries that are affected by the given changed paths. */
    public List<Entry> getEntriesFor(Collection<String> changedPaths) {
        List<Entry> entries = new ArrayList<>();
        for (Entry entry : this.plugins.values()) {
            if (entry.configPaths == null || entry.configPaths.isEmpty()) {
                continue;
            }
            for (String path : changedPaths) {
                if (entry.matches(path)) {
                    entries.add(entry);
                    break;
                }
            }
        }
        return entries;
    }

    /** Reload commands of every plugin touched by the given changed paths, in pack.json order. */
    public List<String> reloadCommandsFor(Collection<String> changedPaths) {
        return commandsOf(getEntriesFor(changedPaths));
    }

    /** Reload commands of every plugin in the pack, in pack.json order. */
    public List<String> allReloadCommands() {
        return commandsOf(this.plugins.values());
    }

    private static List<String> commandsOf(Collection<Entry> entries) {
        return entries.stream()
            // The key is optional in pack.json, gson leaves the field null when it is missing
            .flatMap(entry -> entry.reloadCommands == null ? Stream.<String>empty() : entry.reloadCommands.stream())
            .distinct()
            .toList();
    }

    private static String normalize(String path) {
        return path.replace('\\', '/').replaceAll("^/+", "").replaceAll("/+$", "");
    }
}
